### ISSUE TITLE
开发网evm合约获取的账户地址是alaya格式的

### ISSUE THREAD

**Issue by hthuang996** [PlatONnetwork/client-sdk-js#59]
#### Expected behavior
使用client-sdk-js获取开发网evm合约中的账户地址

#### Actual behavior
得到的是alaya格式的地址：lax1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmscn5j

#### Steps to reproduce the behavior

1. 部署合约继承ownerable合约
2. 编写js代码，调用合约的renounceOwnership方法，实现如下
 _owner = address(uint160(0));
3. 获取_owner地址，得到lax1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqmscn5j

#### Versions
OS: windows
sdk: PlatONnetwork/client-sdk-js#0.15.1-develop

**Comment by luo-dahui** [comment]
创建合约对象时，请指定虚机类型和地址格式前缀，相关文档描述参考：
https://devdocs.platon.network/docs/zh-CN/JS_SDK/#web3platoncontract
