### ISSUE TITLE
The v implementation of web3.platon.accounts.sign is not match with PlatON-Go

### ISSUE THREAD

**Issue by wuyahuang** [PlatONnetwork/client-sdk-js#63]
https://forum.latticex.foundation/t/topic/5332

**Comment by biganxin** [comment]
![image](https://user-images.githubusercontent.com/29141931/127251652-43c6eb70-929c-44b5-b8d6-8c6d2a7f3ce0.png)
What do you think? @luo-dahui

**Comment by biganxin** [comment]
Who can fix it? 
@ariesjia  @RileyGe  @wuyahuang

**Comment by luo-dahui** [comment]
1.目前js-sdk交易相关的签名使用web3.platon.accounts.signTransaction是没有问题的;
2.使用web3.platon.accounts.sign签名数据时v值会有问题，因为没有使用eip155的签名规则，
可参考web3.platon.accounts.signTransaction的签名方式进行修复，如：
var sig = ethereumjs_util_1.ecsign(msgHash, privateKey);
sig.v += this.getChainId() * 2 + 8;
具体实现可根据实际情况进行修改；

**Comment by RileyGe** [comment]
我可以试一下，感觉不是很难，但是最近比较忙，速度可能会比较慢。如果不着急，我就先研究研究代码。

**Comment by ariesjia** [comment]
我可以来尝试一下

**Comment by biganxin** [comment]
cool, If you have any questions, feel free to contact

> 我可以来尝试一下

**Comment by wuyahuang** [comment]
[fix web3.platon.accounts.sign #81](https://github.com/PlatONnetwork/client-sdk-js/pull/81)
