### ISSUE TITLE
js-sdk获取address与实际结果不符

### ISSUE THREAD

**Issue by shadow-001** [PlatONnetwork/client-sdk-js#66]
操作步骤：
1. 调用合约的方法，更改address类型的属性值；
![image](https://user-images.githubusercontent.com/25794754/128852441-981765e8-a5e2-4545-bc0f-35c1908e9959.png)

2. 调用合约的查询方法，查询该属性值，显示结果与实际值不一致
![image](https://user-images.githubusercontent.com/25794754/128852381-722e4b04-58e1-4044-8820-a44b1bdd70e7.png)

结果异常：
![image](https://user-images.githubusercontent.com/25794754/128852578-9db79286-5634-4e9a-9c9e-02ae59cf3b2c.png)
而使用java-sdk调用返回的结果是正确的：
![image](https://user-images.githubusercontent.com/25794754/128852764-f4f03702-2be3-422b-a219-2c4b269467c5.png)

合约源文件：

pragma solidity =0.5.17;

// pragma experimental ABIEncoderV2;

/**
    记录platon上一些报错的代码
 */
contract ErrorNode{

    address public creatorAddr;
    uint public createTime;

    address public pairAddress;

    uint public totalAge;
    struct UserInfo{
        address user;
        uint age;
    }

    constructor() public{
        creatorAddr = msg.sender;
        createTime = block.timestamp + 180000;
    }
    
    /**
    
        require信息未返回：https://github.com/PlatONnetwork/PlatON-Go/issues/1819
     */
    function addTime(address to) external returns(uint){
        require(createTime < now,"too early");
        creatorAddr = to;
        createTime = block.timestamp + 1000;
    }

    // /**
    //     含结构体，生成java文件报错：https://github.com/PlatONnetwork/client-sdk-java/issues/86
    //  */
    // function registerUser(UserInfo[] memory UserInfos) public {
    //     for(uint256 i = 0; i < UserInfos.length; i++){
    //         totalAge = totalAge + UserInfos[i].age;
    //     }
    // }

    /**
        js-sdk与java-sdk返回的结果不一致
     */
    function setPair(address creatorAddress,address _pairAddress) external {
        creatorAddr = creatorAddress;
        pairAddress = _pairAddress;
    }
}

**Comment by luo-dahui** [comment]
请在创建合约对象的时候，指定虚机类型(vmType)和hrp类型(net_type)，如：
new web3.platon.Contract(ErrorNode, contractAddress, {vmType: 0, net_type: 'lat'});

**Comment by shadow-001** [comment]
> 请在创建合约对象的时候，指定虚机类型(vmType)和hrp类型(net_type)，如：
> new web3.platon.Contract(ErrorNode, contractAddress, {vmType: 0, net_type: 'lat'});

加了，还是有问题：
![image](https://user-images.githubusercontent.com/25794754/128975843-871bbc06-2854-4bc0-b9cb-6cfa8795c59d.png)
![image](https://user-images.githubusercontent.com/25794754/128975888-c7d769cb-b3b2-43bb-b033-3ae46493103f.png)


而且文档中提示是有默认值的：
![image](https://user-images.githubusercontent.com/25794754/128975683-70407dd7-a286-44b7-b80c-b601ca7d825d.png)

**Comment by biganxin** [comment]
@luo-dahui
