### ISSUE TITLE
client-sdk-js找不到platon对象

### ISSUE THREAD

**Issue by dqdeep** [PlatONnetwork/client-sdk-js#79]
通过一下代码引入js-sdk找不到platon对象

`    

     <script src="./web3.min.js"></script>

    <script>
        console.log(new Web3());
    </script>
`
同时使用命令npm i PlatONnetwork/client-sdk-js#master 
然后使用import引入 web3 提示 找不到 node_modules\web3\lib\index.js 文件

**Comment by dqdeep** [comment]
补充一下, 这是在浏览器使用的

**Comment by biganxin** [comment]
@luo-dahui @fksyuan  Explain the solution here

**Comment by luo-dahui** [comment]
使用dist/web3p.js这个文件
